MODEL:
  NAME: "deeplab_resnet101"
  WEIGHTS: 'https://download.pytorch.org/models/resnet101-5d3b4d8f.pth'
DATASETS:
  SOURCE_TRAIN: "gta5_train"
  TARGET_TRAIN: "cityscapes_train"
  TEST: "cityscapes_train"
INPUT:
  SOURCE_INPUT_SIZE_TRAIN: (1280, 720)
SOLVER:
  BATCH_SIZE_VAL: 1
